use_frameworks!

platform :ios, '8.0'

target 'jsMyFirstPodWIthLabel_Example' do
  pod 'jsMyFirstPodWIthLabel', :path => '../'

  target 'jsMyFirstPodWIthLabel_Tests' do
    inherit! :search_paths

    
  end
end
